mutation createUnifiedLoggingFilter(
  $name: String!
  $description: String
  $tags: [String]!
  $filter: String!
  $enabled: Boolean
  $level: UNIFIED_LOGGING_LEVEL!
) {
  createUnifiedLoggingFilter(
    input: {
      name: $name
      description: $description
      tags: $tags
      filter: $filter
      enabled: $enabled
      level: $level
    }
  ) {
    ...UnifiedLoggingFilterFields
    __typename
  }
}

fragment UnifiedLoggingFilterFields on UnifiedLoggingFilter {
  uuid
  name
  description
  created
  updated
  filter
  tags
  enabled
  level
  __typename
}
