mutation createGroup($name: String!, $connectionId: ID, $accessGroup: Boolean, $roleIds: [ID], $RBAC_Connection: Boolean!, $RBAC_Role: Boolean!) {
  createGroup(
    input: {name: $name, connectionId: $connectionId, accessGroup: $accessGroup, roleIds: $roleIds}
  ) {
    ...GroupFields
    __typename
  }
}

fragment GroupFields on Group {
  id
  name
  connection @include(if: $RBAC_Connection) {
    id
    name
    __typename
  }
  assignedRoles @include(if: $RBAC_Role) {
    id
    name
    __typename
  }
  accessGroup
  created
  updated
  __typename
}
