mutation createTelemetryV2(
  $name: String!
  $description: String
  $logFiles: [String!]!
  $logFileCollection: Boolean!
  $performanceMetrics: Boolean!
  $events: [ES_EVENTS_ENUM]!
  $fileHashing: Boolean!
  $RBAC_Plan: Boolean!
) {
  createTelemetryV2(
    input: {
      name: $name
      description: $description
      logFiles: $logFiles
      logFileCollection: $logFileCollection
      performanceMetrics: $performanceMetrics
      events: $events
      fileHashing: $fileHashing
    }
  ) {
    ...TelemetryV2Fields
    __typename
  }
}

fragment TelemetryV2Fields on TelemetryV2 {
  id
  name
  description
  created
  updated
  logFiles
  logFileCollection
  performanceMetrics
  plans @include(if: $RBAC_Plan) {
    id
    name
    __typename
  }
  events
  fileHashing
  __typename
}
