query getAlertStatusCounts {
  infoStatusCount: getAlertStatusCounts(
    input: {severity: {equals: Informational}}
  ) {
    New
    AutoResolved
    InProgress
    Resolved
    __typename
  }
  lowStatusCount: getAlertStatusCounts(input: {severity: {equals: Low}}) {
    New
    AutoResolved
    InProgress
    Resolved
    __typename
  }
  mediumStatusCount: getAlertStatusCounts(input: {severity: {equals: Medium}}) {
    New
    AutoResolved
    InProgress
    Resolved
    __typename
  }
  highStatusCount: getAlertStatusCounts(input: {severity: {equals: High}}) {
    New
    AutoResolved
    InProgress
    Resolved
    __typename
  }
}
