query getStatsSeverityTimeSeries($interval: String!, $since: String!, $timezone: String, $computerFilter: [AlertFiltersInput!]) {
  infoTimeSeries: listAlertsTimeSeries(
    input: {filter: {and: $computerFilter, severity: {equals: Informational}}, interval: $interval, timezone: $timezone, since: $since}
  ) {
    timeInterval
    count
    __typename
  }
  lowTimeSeries: listAlertsTimeSeries(
    input: {filter: {and: $computerFilter, severity: {equals: Low}}, interval: $interval, timezone: $timezone, since: $since}
  ) {
    timeInterval
    count
    __typename
  }
  mediumTimeSeries: listAlertsTimeSeries(
    input: {filter: {and: $computerFilter, severity: {equals: Medium}}, interval: $interval, timezone: $timezone, since: $since}
  ) {
    timeInterval
    count
    __typename
  }
  highTimeSeries: listAlertsTimeSeries(
    input: {filter: {and: $computerFilter, severity: {equals: High}}, interval: $interval, timezone: $timezone, since: $since}
  ) {
    timeInterval
    count
    __typename
  }
  infoStatusCount: getAlertStatusCounts(
    input: {severity: {equals: Informational}, and: [{and: $computerFilter, created: {afterInterval: $since}}]}
  ) {
    New
    AutoResolved
    InProgress
    Resolved
    __typename
  }
  lowStatusCount: getAlertStatusCounts(
    input: {severity: {equals: Low}, and: [{and: $computerFilter, created: {afterInterval: $since}}]}
  ) {
    New
    AutoResolved
    InProgress
    Resolved
    __typename
  }
  mediumStatusCount: getAlertStatusCounts(
    input: {severity: {equals: Medium}, and: [{and: $computerFilter, created: {afterInterval: $since}}]}
  ) {
    New
    AutoResolved
    InProgress
    Resolved
    __typename
  }
  highStatusCount: getAlertStatusCounts(
    input: {severity: {equals: High}, and: [{and: $computerFilter, created: {afterInterval: $since}}]}
  ) {
    New
    AutoResolved
    InProgress
    Resolved
    __typename
  }
}
