query listAnalyticSets(
  $nextToken: String
  $direction: OrderDirection = DESC
  $field: AnalyticSetOrderField = created
  $filter: AnalyticSetFiltersInput = { and: [{ managed: { equals: false } }] }
  $RBAC_Plan: Boolean!
  $excludeAnalytics: Boolean = false
) {
  listAnalyticSets(
    input: {
      next: $nextToken
      order: { direction: $direction, field: $field }
      pageSize: 100
      filter: $filter
    }
  ) {
    items {
      ...AnalyticSetFields
      __typename
    }
    pageInfo {
      next
      total
      __typename
    }
    __typename
  }
}

fragment AnalyticSetFields on AnalyticSet {
  uuid
  name
  description
  analytics @skip(if: $excludeAnalytics) {
    uuid
    name
    jamf
    __typename
  }
  plans @include(if: $RBAC_Plan) {
    id
    name
    __typename
  }
  created
  updated
  managed
  types
  __typename
}
