query listAnalyticsLite {
  listAnalytics {
    items {
      name
      label
      uuid
      longDescription
      description
      tags
      inputType
      remediation
      __typename
    }
    pageInfo {
      next
      total
      __typename
    }
    __typename
  }
}
