query listAlerts($nextToken: String, $pageSize: Int = 100, $field: AlertOrderField!, $direction: OrderDirection!, $filter: AlertFiltersInput) {
  listAlerts(
    input: {next: $nextToken, pageSize: $pageSize, filter: $filter, order: {direction: $direction, field: $field}}
  ) {
    items {
      ...AlertFields
      __typename
    }
    pageInfo {
      next
      total
      __typename
    }
    __typename
  }
}

fragment AlertFields on Alert {
  uuid
  created
  status
  severity
  actions
  tags
  eventType
  plan {
    uuid
    name
    __typename
  }
  computer {
    uuid
    hostName
    modelName
    plan {
      id
      name
      __typename
    }
    __typename
  }
  analytics {
    name
    label
    description
    uuid
    __typename
  }
  facts {
    name
    tags
    human
    actions {
      name
      __typename
    }
    __typename
  }
  __typename
}
