name: Acceptance Tests

on:
  workflow_run:
    workflows: ["Integration Tests"]
    types: [completed]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  acceptance:
    name: Acceptance Tests (Terraform ${{ matrix.terraform }})
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: acceptance
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        terraform:
          - "1.13.*"
          - "1.14.*"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: "go.mod"
          cache: true
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - run: go mod download
      - run: go test -v -cover -count=1 -p=1 ./...
        timeout-minutes: 30
        env:
          TF_ACC: "1"
          JAMFPROTECT_URL: ${{ secrets.JAMFPROTECT_URL }}
          JAMFPROTECT_CLIENT_ID: ${{ secrets.JAMFPROTECT_CLIENT_ID }}
          JAMFPROTECT_CLIENT_SECRET: ${{ secrets.JAMFPROTECT_CLIENT_SECRET }}
